// ---- Core data model ----

export type TaskStatus = 'not_started' | 'in_progress' | 'at_risk' | 'done'

export interface Project {
  id: string
  name: string
  description: string
  startDate: string
  endDate: string
  color: string
  createdAt: string
  updatedAt: string
}

export interface Member {
  id: string
  name: string
  email?: string
  color: string
  createdAt: string
}

export interface Task {
  id: string
  projectId: string
  moduleId?: string | null   // EXC-1 (M5.1 C): modules can own Gantt tasks
  name: string
  notes: string
  startDate: string
  endDate: string
  status: TaskStatus
  percentComplete: number
  isMilestone: boolean
  assigneeIds: string[]
  recurring: null | {
    interval: 'daily' | 'weekly' | 'monthly'
    until?: string
  }
  createdAt: string
  updatedAt: string
}

export interface Dependency {
  predecessorId: string
  successorId: string
}

export interface Holiday {
  id: string
  date: string
  name: string
  recurring?: 'yearly' | null
  createdAt: string
}

export type UpdateSignal = 'green' | 'yellow' | 'red' | 'neutral'

export interface ProjectUpdate {
  id: string
  projectId: string
  text: string
  signal: UpdateSignal
  authorMemberId?: string
  createdAt: string
  // System-generated updates (e.g. "Architecture marked done") set this to true
  // so the UI can display them slightly differently (dimmer, no delete option).
  autoGenerated?: boolean
}

// ---- Phase tracking ----

/**
 * PhaseTemplate is a reusable phase definition in the global library.
 * Editing a template's name updates every project using it.
 * Examples: "Requirements Gathering", "Architecture Finalizing", "UX Design".
 */
export interface PhaseTemplate {
  id: string
  name: string
  description?: string
  color: string
  createdAt: string
}

export type PhaseStatus = 'not_started' | 'in_progress' | 'blocked' | 'done' | 'skipped'

/**
 * ProjectPhase is a phase template applied to a specific project. The same
 * template can be used in many projects; each project tracks its own progress
 * and dates independently.
 *
 * - `order` controls the left-to-right position in the pipeline strip.
 * - `startedAt` / `completedAt` are auto-filled when status transitions, but
 *   editable. They drive "this phase took 3 weeks" retrospective questions.
 */
export interface ProjectPhase {
  id: string
  projectId: string
  templateId: string
  order: number
  status: PhaseStatus
  startedAt?: string   // ISO timestamp; auto-set when status → in_progress
  completedAt?: string // ISO timestamp; auto-set when status → done
  notes?: string
  createdAt: string
}

export interface TibbieData {
  projects: Project[]
  members: Member[]
  tasks: Task[]
  dependencies: Dependency[]
  holidays: Holiday[]
  updates: ProjectUpdate[]
  phaseTemplates: PhaseTemplate[]
  projectPhases: ProjectPhase[]
  version: number
  // V2 fields — never destructive, V1 fields above are untouched
  schemaVersion?: number
  projectsV2?: ProjectV2[]
  featuresV2?: FeatureV2[]
  userPresets?: { name: string; filter: Record<string, unknown> }[]
  deletionLog?: DeletionLogEntry[]   // CR-2.3: permanent deletion audit trail
  _v1ProjectsBackup?: Project[]      // schemaVersion 3: migration safety net, no UI
  // Phase C: workspace-level settings (scoring framework etc.)
  workspaceSettings?: { framework: 'rice' | 'wsjf' }
  // Phase D: module hierarchy
  modulesV2?: ModuleV2[]
}

// ---- UI state ----

export type ZoomLevel = 'day' | 'week' | 'month'
export type GroupBy = 'project' | 'assignee' | 'none'

export interface Filters {
  projectIds: string[]
  statuses: TaskStatus[]
  memberIds: string[]
  dateRange: { start: string | null; end: string | null }
}

export interface SearchResult {
  type: 'project' | 'task' | 'member'
  id: string
  label: string
  sublabel?: string
  matchField?: 'name' | 'notes' | 'description' | 'email'
  projectId?: string
}

// ─────────────────────────────────────────────────────────────────────────────
// V2 DATA MODEL
// ─────────────────────────────────────────────────────────────────────────────

export type EntityKind = 'project' | 'feature'

export type ProjectStatus =
  | 'intake'
  | 'requirement_gathering'
  | 'requirement_analysis'
  | 'architecture'
  | 'development'
  | 'in_testing'
  | 'beta_production'
  | 'production'
  | 'production_monitoring'
  | 'mvp_live'
  | 'on_hold'
  | 'killed'

export type FeatureStatus =
  | 'intake'
  | 'tech_review'
  | 'refinement'
  | 'in_dev'
  | 'code_review'
  | 'qa'
  | 'staging_signoff'
  | 'shipped'
  | 'rework'
  | 'on_hold'
  | 'killed'

export type EffortSize = 'S' | 'M' | 'L' | 'XL'

export type TrackKind = 'marketing' | 'sales' | 'support' | 'implementation'
export type MarketingTrackStatus      = 'not_started' | 'positioning' | 'collateral_ready' | 'launched'
export type SalesTrackStatus          = 'not_started' | 'deck_pricing_ready' | 'team_trained' | 'selling'
export type SupportTrackStatus        = 'not_started' | 'docs_written' | 'team_trained' | 'live'
export type ImplementationTrackStatus = 'not_started' | 'deployment_plan' | 'pilot_client' | 'rolled_out'

export interface RiceScore {
  reach: 1 | 2 | 3 | 4 | 5   // 1=Very few · 2=Some · 3=Many · 4=Most · 5=Nearly all users
  impact: 0.25 | 0.5 | 1 | 2 | 3
  confidence: number       // 0–100
  effort: number           // person-weeks > 0
  scoredAt: string         // ISO date
  scoredBy?: string        // memberId
}

// ── Phase C: WSJF scoring framework ─────────────────────────────────────────
export interface WsjfScore {
  businessValue: number      // 1–10: how much money/strategic value
  timeCriticality: number    // 1–10: cost of delay / urgency
  riskOpportunity: number    // 1–10: risk reduction / opportunity enablement
  jobSize: number            // 1–10: relative effort (bigger = larger)
  scoredAt: string
  scoredBy?: string
  // Derived: (businessValue + timeCriticality + riskOpportunity) / jobSize
}

// ── Phase B: Must-Do tag ──────────────────────────────────────────────────────
export interface MustDoTag {
  reason: string
  at: string          // ISO timestamp when tag was applied
  byMemberId?: string
}

export interface StatusLogEntry {
  id: string
  from: string
  to: string
  at: string               // ISO timestamp
  byMemberId?: string
  note?: string
}

export interface DecisionEntry {
  id: string
  text: string
  at: string
  byMemberId?: string
}

export interface Milestone {
  id: string
  name: string
  date: string
  status: 'upcoming' | 'hit' | 'missed' | 'moved'
  movedFrom?: string
}

export interface DepartmentTrack {
  kind: TrackKind
  status: string
  ownerIds: string[]
  note?: string
  blocked: boolean
  updatedAt: string
  statusLog: StatusLogEntry[]
}

export interface ProjectV2 {
  id: string
  kind: 'project'
  name: string
  oneLiner: string
  portfolio: string
  status: ProjectStatus
  holdReason?: string
  killReason?: string
  ownerIds: string[]
  targetQuarter?: string
  startDate?: string
  targetShipDate?: string
  effortEstimate?: EffortSize
  tags: string[]
  milestones: Milestone[]
  featureIds: string[]
  tracks: DepartmentTrack[]
  statusLog: StatusLogEntry[]
  decisionLog: DecisionEntry[]
  activityLog?: ActivityEntry[]   // Item 6
  retroNotes?: string
  archived: boolean
  order: number             // manual sort within portfolio section
  rice: RiceScore | null          // CR-1.1 — joins unified RICE rank pool
  wsjf: WsjfScore | null         // Phase C — WSJF framework alternative to RICE
  valueRating?: 1 | 2 | 3 | 4 | 5  // CR-1.4 — Business Value (independent of RICE)
  mustDo?: MustDoTag             // Phase B — Must-Do: excluded from rank pool, ships regardless
  clientTimeline?: boolean       // Phase B — Timeline has been shared with client (caution signal)
  // ── Unification fields (schemaVersion 3) ──────────────────────────────────
  color?: string        // Gantt bar color — migrated from V1 Project
  ganttStart?: string   // ISO date for Gantt display
  ganttEnd?: string     // ISO date for Gantt display
  createdAt: string
  updatedAt: string
}

export interface FeatureV2 {
  id: string
  kind: 'feature'
  name: string
  oneLiner: string
  projectId: string | null
  status: FeatureStatus
  reworkFromGate?: 'architecture' | 'code_review' | 'qa'
  holdReason?: string
  killReason?: string
  itemType?: 'feature' | 'improvement'   // default 'feature' — backfilled by compat patch
  rice: RiceScore | null
  wsjf: WsjfScore | null         // Phase C — WSJF framework alternative to RICE
  valueRating?: 1 | 2 | 3 | 4 | 5  // CR-1.4
  effortEstimate?: EffortSize
  ownerIds: string[]
  tags: string[]
  statusLog: StatusLogEntry[]
  decisionLog: DecisionEntry[]
  activityLog?: ActivityEntry[]   // Item 6
  archived: boolean
  mustDo?: MustDoTag             // Phase B — Must-Do: ships regardless of score
  order: number
  moduleId?: string | null       // Phase D: null = directly under project or backlog
  createdAt: string
  updatedAt: string
}

// ── CR-1 additions ────────────────────────────────────────────────────────────
// Applied via module augmentation pattern — extend interfaces by re-exporting
// (TypeScript doesn't allow partial interface re-declaration in the same file,
// so these fields are added here as documentation and picked up by the compiler
// via the full interface definitions updated in-place above)
// NOTE: actual field additions are in types.ts ProjectV2/FeatureV2 above.

// ── Item 6: Activity Log ───────────────────────────────────────────────────────
export type ActivityTag = 'Meeting' | 'Blocker' | 'Update' | 'Decision'
export type SystemEventType =
  | 'status_change' | 'created' | 'assignment' | 'track_update'
  | 'must_do' | 'archived' | 'restored' | 'migrated'

export interface ActivityEntry {
  id: string
  at: string       // ISO timestamp
  kind: 'system' | 'user'
  text: string
  tag?: ActivityTag
  authorId?: string
  systemEventType?: SystemEventType
}
export interface ModuleV2 {
  id: string
  kind: 'module'
  name: string
  oneLiner?: string
  projectId: string             // modules ALWAYS belong to a project
  status: FeatureStatus         // same ladder as features
  holdReason?: string
  killReason?: string
  reworkFromGate?: 'architecture' | 'code_review' | 'qa'
  ownerIds: string[]
  mustDo?: MustDoTag
  rice: RiceScore | null
  wsjf: WsjfScore | null
  valueRating?: 1|2|3|4|5
  statusLog: StatusLogEntry[]
  decisionLog: DecisionEntry[]
  activityLog?: ActivityEntry[]   // Item 6
  archived: boolean
  createdAt: string
  updatedAt: string
  // ── EXC-1 (M5.1 C): modules as first-class roadmap citizens ──────────────
  portfolio?: string            // grouping; absent = inherit parent project's
  milestones: Milestone[]       // same shape as ProjectV2
  tracks: DepartmentTrack[]     // department readiness (same shape as ProjectV2)
  clientTimeline?: boolean      // caution signal, same as ProjectV2
  effortEstimate?: EffortSize   // for card anatomy
  targetQuarter?: string        // for card anatomy
}

// ── CR-2 additions ────────────────────────────────────────────────────────────
export interface DeletionLogEntry {
  id: string          // uid of deleted item
  name: string
  kind: 'project' | 'feature' | 'module'   // R2-L1: widened to include modules
  deletedAt: string   // ISO timestamp
}
